### PR TITLE
fix nodeJS crash when errornous ical is given

### PR DESCRIPTION
**Pull request by maksimluzik**
Added try catch for parsing the date toISOString to prevent complete application crash on fail.

### CODE REVIEW

**Comment by tnguyen14** [comment]
@peterbraden can this be merged? Would be great to not have to try catch in the application code.

**Comment by peterbraden** [comment]
hi, sorry for the slow response - can you fix the merge conflict then I can merge

**Comment by maksimluzik** [comment]
Resolved conflicts

**Comment by tnguyen14** [comment]
Please update here when a new version is released.

**Pull request merged**
