### PR TITLE
Suggested fix for issue #72

### PR DESCRIPTION
**Pull request by mwittig**
Return error in fromURL() if HTTP response status is >= 400, issue #72

### CODE REVIEW

**Comment by peterbraden** [comment]
I think it would be better to just pass the response in the error body,
rather than implementing any HTTP codes etc, ie:

  request(url, opts, function(err, r, data){
     if (err) {
       return cb(err, r);
  }
 cb(undefined, ical.parseICS(data));
}

--

Peter Braden

http://PeterBraden.co.uk

**Comment by mwittig** [comment]
> I think it would be better to just pass the response in the error body, ...

Well, the point is that a response status >= 400 does not trigger an error result from the request() method.  According to the docs a request error basically what is returned as error by http.ClientRequest which in turn is mainly a socket error. Thus application layer errors need to be handled by the application as can also be seen in the examples given for the reuqets package. See also:
* paragraph above section "Convenience methods" - https://www.npmjs.com/package/request#convenience-methods
* https://nodejs.org/api/http.html#http_class_http_clientrequest

**Comment by kcrosley-leisurelabs** [comment]
This is still an issue (it's otherwise great, BTW)...  I use the fromURL() form of this package. If the URL does not exist or some other type of HTTP error happens, there is no error and no feedback as to why things failed. All I can tell is that data is empty. Would greatly appreciate a fix for this and @mwittig's approach looks like a good one.

Any chance of a fix for this?

**Comment by peterbraden** [comment]
see #110

**Pull request closed without merging**
